### ISSUE TITLE
Optimization: Graph traverse followed by type check

### ISSUE THREAD

**Issue by JNKHunter** [gsk-aiops/bellman#106]
Traversing the graph is frequently followed by a "filter" for a particular class. For example. `?d dm:contains ?ds` will frequently be followed by `?ds a dm:SomeClass` in order to filter out results of `dm:SomeOtherClass`.

Explore solutions for filtering on `?ds a dm:SomeClass` during the scan for `?d dm:contains ?ds`. This could result in one less join for this particular BGP pattern.

It's likely we may need a technology like RDF* or simply introduce new connections to perform this filter in one scan.

Example:
```
WHERE
{
  ?d a dm:Section .
  ?d dm:contains ?ds .
  ?ds a dm:SomeClass .
}
```

**Comment by pepegar** [comment]
This one is currently achieved by BGP compaction, given the two first triples share a variable in the same position.

In the end it will perform something like (SparQLike):

```
WHERE
{
  ?d a dm:Section  && ?d dm:contains ?ds . #1
  ?ds a dm:SomeClass . #2
}
```

We'll only pushing down two scans to the DF in this case, one for the first two triples, one for the last one.

**Comment by JNKHunter** [comment]
Thanks @pepegar ! Closing.
