### ISSUE TITLE
Blank node in construct should produce unique blank node label per solution

### ISSUE THREAD

**Issue by JNKHunter** [gsk-aiops/bellman#107]
As per spec:
https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#templatesWithBNodes

_"A template can create an RDF graph containing blank nodes. The blank node labels are scoped to the template for each solution. If the same label occurs twice in a template, then there will be one blank node created for each query solution, but there will be different blank nodes for triples generated by different query solutions."_

Currently, is seems our solution is creating a single blank node (using a UUID), and reusing for each solution in the result.
![image](https://user-images.githubusercontent.com/2665766/110111161-e4ec2f80-7d7d-11eb-99e8-5dbcaa72a805.png)

**Comment by pepegar** [comment]
In this case, we're picking the generated IDs from what Jena ARQ generates:

https://github.com/gsk-aiops/bellman/blob/master/modules/parser/src/main/scala/com/gsk/kg/sparqlparser/QueryConstruct.scala#L35

And, in our internal DAG, we already get the UUIDS.  you can see the UUIDs DAG we get in the DAG from Jena here:
 
```sparql
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX vcard:   <http://www.w3.org/2001/vcard-rdf/3.0#>

CONSTRUCT {
  ?x vcard:N _:v .
  _:v vcard:givenName ?gname .
  _:v vcard:family_name ?fname
} WHERE {
  ?x foaf:firstname ?gname .
  ?x foaf:family_name ?fname .
}
```

DAG:

```
Construct
|
+- BGP
|  |
|  +- Triple
|  |  |
|  |  +- ?x
|  |  |
|  |  +- http://www.w3.org/2001/vcard-rdf/3.0#N
|  |  |
|  |  `- 0be8617b-140a-425b-8f97-9d450b0a7bba
|  |
|  +- Triple
|  |  |
|  |  +- 0be8617b-140a-425b-8f97-9d450b0a7bba
|  |  |
|  |  +- http://www.w3.org/2001/vcard-rdf/3.0#givenName
|  |  |
|  |  `- ?gname
|  |
|  `- Triple
|     |
|     +- 0be8617b-140a-425b-8f97-9d450b0a7bba
|     |
|     +- http://www.w3.org/2001/vcard-rdf/3.0#family_name
|     |
|     `- ?fname
|
`- BGP
   |
   +- Triple
   |  |
   |  +- ?x
   |  |
   |  +- http://xmlns.com/foaf/0.1/firstname
   |  |
   |  `- ?gname
   |
   `- Triple
      |
      +- ?x
      |
      +- http://xmlns.com/foaf/0.1/family_name
      |
      `- ?fname
```

I'm taking a look at how this is handled internally in Jena ARQ, but seems that Jena just generates one UUID per blank node template.
