### ISSUE TITLE
Add support for filtering over entire select statement

### ISSUE THREAD

**Issue by JNKHunter** [gsk-aiops/bellman#115]
Example of filtering over a select:

https://github.com/gsk-aiops/bellman/blob/6327df4d52c367ae6075200628a3532c4bb0ab02/modules/parser/src/test/scala/com/gsk/kg/sparqlparser/QuerySamples.scala#L55

**Comment by patofp** [comment]
Right now we already have some tests that filters over a select statement as in [here](https://github.com/gsk-aiops/bellman/blob/506df5794d77851dd379a551bdd2dc25911e99fa/modules/engine/src/test/scala/com/gsk/kg/engine/CompilerSpec.scala#L563), and it seems it works fine.

But there is something that made me think about that sample query @JNKHunter. It seems like if within the result of the query was expected to contain all superclasses transitively by inference. 

So I stated a little research on this by doing a similar test:

I created a KG:

```
@prefix : <http://example.org/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

:Network rdfs:subClassOf :Main .

:ATM rdfs:subClassOf :Network .
:ARPANET rdfs:subClassOf :Network .

:Software rdfs:subClassOf :Main .

:Linux rdfs:subClassOf :Software .
:Windows rdfs:subClassOf :Software .

:XP rdfs:subClassOf :Windows .
:Win7 rdfs:subClassOf :Windows .
:Win8 rdfs:subClassOf :Windows .
```

And a Sparql query:
```
PREFIX : <http://example.org/>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?parent
WHERE {
    :Win8 rdf:subClassOf ?parent .
    FILTER (!isBlank(?parent))
}
```

So the expected result with **transitive inference** should be:

```
:Main
:Software
:Windows
```

And without inference:
```
:Windows
```

1. I run this query with this dataset on our engine and I've got:
```
:Windows
```

2. And then I run on GraphDB, and I got:
```
:Main
:Software
:Windows
```
It seems they have an option to do the **inference**

3. I run on Jena and got:
```
:Windows
```
As this is our reference, and in our engine we got the same result, I'll give it as a valid result, but it is something that maybe we have to take into bellmans at some time. What do you think @JNKHunter, @pepegar ?

PD: It is really simple to run something on Jena, here is some example:

![Captura de pantalla 2021-03-10 a las 17 28 09](https://user-images.githubusercontent.com/6108743/110669838-0d848700-81cd-11eb-82a4-31d62249c8af.png)

**Comment by JNKHunter** [comment]
Thanks for the investigation @patofp ! For the time being, we are not supporting inference. However as we build features, we will want to have some form of inferencing supported. 

Sansa stack offers some reasoning algorithms. We can have a look after Q2: https://github.com/SANSA-Stack/SANSA-Stack/tree/develop/sansa-inference
