### ISSUE TITLE
Difference between Apache Jena and Bellman results

### ISSUE THREAD

**Issue by bkosuru** [gsk-aiops/bellman#188]
SELECT DISTINCT ?label
WHERE {
  <http://purl.obolibrary.org/obo/CLO_0052588>
  <http://www.w3.org/2000/01/rdf-schema#label>
  ?label.
}

Jena: (This is csv output)
+-------------+
|label        |
+-------------+
|NICR2579 cell|
|NICR2579 细胞|
+-------------+

Bellman: (bug: values have quotes around text with @en and @zh)

+--------------------------+
|label                     |
+--------------------------+
|"NICR2579 \u7EC6\u80DE"@zh|
|"NICR2579 cell"@en        |
+--------------------------+

unicode code points(\u7EC6\u80DE) instead of characters(细胞) is ok. The input data has unicode code points.

**Comment by bkosuru** [comment]
May be there is some inconsistency with Jena.
For this query,
CONSTRUCT {<http://purl.obolibrary.org/obo/CLO_0052588> <http://www.w3.org/2000/01/rdf-schema#label> ?label}
WHERE {
  <http://purl.obolibrary.org/obo/CLO_0052588> <http://www.w3.org/2000/01/rdf-schema#label> ?label .
}

Jena output is: (Note that this nt output)
<http://purl.obolibrary.org/obo/CLO_0052588> <http://www.w3.org/2000/01/rdf-schema#label> "NICR2579 细胞"@zh .
<http://purl.obolibrary.org/obo/CLO_0052588> <http://www.w3.org/2000/01/rdf-schema#label> "NICR2579 cell"@en .

**Comment by JNKHunter** [comment]
We are mainly using Jena to make sure counts and rows returned are correct. As far as format, we do not necessarily have to ensure Bellman output matches Jena 1:1 and can make that call on a case by case basis.

Please work with Bindu to understand the problem.

**Comment by patofp** [comment]
I think this is due to Jena output formatter. Hope this test gives some light on the subject:

I created a dataset **languages.ttl**:
```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix t: <http://tuples.org/> .
t:a foaf:lang "NICR2579 \u7EC6\u80DE"@zh .
t:b foaf:lang "NICR2579 cell"@en .
t:c foaf:lang "NICR2579 cell" .
t:d foaf:lang "NICR2579 细胞" .
```

And a simple query *languages.rq*:
```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?x ?lit
WHERE {
  ?x foaf:lang ?lit
}
```

Then I load the dataset into Apache Fuseki on de default graph:
```
s-put http://localhost:3030/ds default ~/tmp/rdf-datasets/languages.ttl -v
```

And then trigger queries with different output formats based on `s-query` output types {csv, tsv, json, xml, text} :

```
s-query --service=http://localhost:3030/ds --file=languages.rq --output={csv|tsv|json|xml|text} -v
```

*Text*:
```
----------------------------------------------
| x                     | lit                |
==============================================
| <http://tuples.org/c> | "NICR2579 cell"    |
| <http://tuples.org/b> | "NICR2579 cell"@en |
| <http://tuples.org/d> | "NICR2579 细胞"      |
| <http://tuples.org/a> | "NICR2579 细胞"@zh   |
----------------------------------------------
```

*CSV*:
```
http://tuples.org/c,NICR2579 cell
http://tuples.org/b,NICR2579 cell
http://tuples.org/d,NICR2579 细胞
http://tuples.org/a,NICR2579 细胞
```

*TSV*:
```
?x	?lit
<http://tuples.org/c>	"NICR2579 cell"
<http://tuples.org/b>	"NICR2579 cell"@en
<http://tuples.org/d>	"NICR2579 细胞"
<http://tuples.org/a>	"NICR2579 细胞"@zh
```

*XML*:
```
<?xml version="1.0"?>
<sparql xmlns="http://www.w3.org/2005/sparql-results#">
  <head>
    <variable name="x"/>
    <variable name="lit"/>
  </head>
  <results>
    <result>
      <binding name="x">
        <uri>http://tuples.org/c</uri>
      </binding>
      <binding name="lit">
        <literal>NICR2579 cell</literal>
      </binding>
    </result>
    <result>
      <binding name="x">
        <uri>http://tuples.org/b</uri>
      </binding>
      <binding name="lit">
        <literal xml:lang="en">NICR2579 cell</literal>
      </binding>
    </result>
    <result>
      <binding name="x">
        <uri>http://tuples.org/d</uri>
      </binding>
      <binding name="lit">
        <literal>NICR2579 细胞</literal>
      </binding>
    </result>
    <result>
      <binding name="x">
        <uri>http://tuples.org/a</uri>
      </binding>
      <binding name="lit">
        <literal xml:lang="zh">NICR2579 细胞</literal>
      </binding>
    </result>
  </results>
</sparql>
```

*JSON*:
```
{ "head": {
    "vars": [ "x" , "lit" ]
  } ,
  "results": {
    "bindings": [
      {
        "x": { "type": "uri" , "value": "http://tuples.org/c" } ,
        "lit": { "type": "literal" , "value": "NICR2579 cell" }
      } ,
      {
        "x": { "type": "uri" , "value": "http://tuples.org/b" } ,
        "lit": { "type": "literal" , "xml:lang": "en" , "value": "NICR2579 cell" }
      } ,
      {
        "x": { "type": "uri" , "value": "http://tuples.org/d" } ,
        "lit": { "type": "literal" , "value": "NICR2579 细胞" }
      } ,
      {
        "x": { "type": "uri" , "value": "http://tuples.org/a" } ,
        "lit": { "type": "literal" , "xml:lang": "zh" , "value": "NICR2579 细胞" }
      }
    ]
  }
}
```

In all cases Unicode entity **NICR2579 \u7EC6\u80DE** is being decoded to **NICR2579 细胞**.
When formatted in *CSV*, the @en and @zsh is not preserved as in *TEXT* or *TSV* formats.

In the future we can create in the engine different formatters as Jena does so it can be configured to throw outputs in different formats.

**Comment by bkosuru** [comment]
@patofp Patricio, Thanks for the details. We only have parquet output. So I am fine with this format.
"NICR2579 cell"@en 

Not sure about decoding Unicode entity. I am fine with whatever you guys decide.

cc: @JNKHunter

**Comment by pepegar** [comment]
@bkosuru is it OK for you then to return the strings formatted as we're doing?   I think that this kind of format that Jena is doing is not part of the SparQL spec.

cc: @patofp @JNKHunter

**Comment by JNKHunter** [comment]
> We are mainly using Jena to make sure counts and rows returned are correct. As far as format, we do not necessarily have to ensure Bellman output format matches Jena 1:1 and can make that call on a case by case basis.
> 

Good to close if our output rows are correct! We are not looking to replicate Jena's output format

**Comment by bkosuru** [comment]
Output rows are correct. You can close this one @patofp
