### ISSUE TITLE
Difference between Apache Jena and Bellman results for REPLACE

### ISSUE THREAD

**Issue by bkosuru** [gsk-aiops/bellman#189]
CONSTRUCT {<http://purl.obolibrary.org/obo/CLO_0037232> ?parent ?msg} WHERE {
  <http://purl.obolibrary.org/obo/CLO_0037232>
  <http://www.w3.org/2000/01/rdf-schema#subClassOf>
  ?parent.
  BIND(REPLACE(\"GOODBYE WORLD\",\"GOODBYE\",\"HELLO\") as ?msg) .
}LIMIT 10

Jena results:
+--------------------------------------------+--------------------------------------------+-----------+
|s                                           |p                                           |o          |
+--------------------------------------------+--------------------------------------------+-----------+
|<http://purl.obolibrary.org/obo/CLO_0037232>|<http://purl.obolibrary.org/obo/CLO_0000853>|HELLO WORLD|
+--------------------------------------------+--------------------------------------------+-----------+

Bellman results:
+--------------------------------------------+--------------------------------------------+-------------+
|s                                           |p                                           |o            |
+--------------------------------------------+--------------------------------------------+-------------+
|<http://purl.obolibrary.org/obo/CLO_0037232>|<http://purl.obolibrary.org/obo/CLO_0000853>|"HELLO WORLD"|
|<http://purl.obolibrary.org/obo/CLO_0037232>|_:N06808eba7ffc4beaa023488d15a1a80f         |"HELLO WORLD"|
+--------------------------------------------+--------------------------------------------+-------------+

**Comment by JNKHunter** [comment]
Please work with Bindu to understand the problem.

**Comment by bkosuru** [comment]
Tomas gets the same results with Jena. Input data used
<http://purl.obolibrary.org/obo/CLO_0037232> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://purl.obolibrary.org/obo/CLO_0000853> .
<http://purl.obolibrary.org/obo/CLO_0037232> <http://www.w3.org/2000/01/rdf-schema#subClassOf> _:N06808eba7ffc4beaa023488d15a1a80f .

@JNKHunter Do you remember using any additional flags to generate single row output?

**Comment by bkosuru** [comment]
![Screenshot 2022-01-07 at 12 34 32](https://user-images.githubusercontent.com/7408351/148770449-ea93ed3f-306b-4057-ad78-3e6a41a4dec2.png)

**Comment by bkosuru** [comment]
Discussed with @JNKHunter. Since the results from Jena and Bellman are identical now, we can close the ticket.
