### ISSUE TITLE
Strip question marks from column names

### ISSUE THREAD

**Issue by JNKHunter** [gsk-aiops/bellman#195]
By default, strip question marks from column names returned from a where block. Give the user the ability to include the question marks with a flag that is passed during the method call: preserveColumnNames true/false. Default false.

This should be performed as an after-execution step, like the `RDFFormatter` step.  The reason for that is that when we introduce subqueries, dependent subquerie may want to access columns resulting from the child ones with the question mark.

**Comment by JNKHunter** [comment]
Let's make sure this feature doesn't clash with subqueries!
https://github.com/gsk-aiops/bellman/issues/156

We will want to make sure we strip question marks as the very last step before returning final DF.

**Comment by patofp** [comment]
It shouldn't clash with subqueries as this is only an output formatting thing. Our RDF formatting is done after engine evaluation:

```
  def compiler(df: DataFrame)(implicit
      sc: SQLContext
  ): Phase[String, DataFrame] =
    parser >>>
      transformToGraph.first >>>
      optimizer >>>
      staticAnalysis >>>
      engine(df) >>>
      rdfFormatter
```
