### ISSUE TITLE
Simple query with LIMIT, long running time

### ISSUE THREAD

**Issue by JNKHunter** [gsk-aiops/bellman#207]
Steps to reproduce on 0.1.12+333-72e54681-SNAPSHOT:

1. Create SPOG Dataframe on 1.5TB data
2. Run the following query:
``` dfg.sparql("""
PREFIX  schema: <http://schema.org/>
PREFIX  rdf:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  xml:  <http://www.w3.org/XML/1998/namespace>
PREFIX  dm:   <http://gsk-kg.rdip.gsk.com/dm/1.0/>
PREFIX  prism: <http://prismstandard.org/namespaces/basic/2.0/>

select ?d ?doi
WHERE{
  ?d a dm:Document .
  ?d prism:doi ?doi
}
LIMIT 10
""").show(10,false)
```

3. Entire dataset is scanned instead of returning first 10 results:
4. Same query using Dataframe commands complete in under 10 seconds

Below are some screenshots from sparkui from long running queries

![image](https://user-images.githubusercontent.com/2665766/114468412-6f178700-9bb9-11eb-9181-ae6f8c9da389.png)
-----
![image](https://user-images.githubusercontent.com/2665766/114468571-b56ce600-9bb9-11eb-9789-70e0cbd879db.png)

**Comment by JNKHunter** [comment]
Same behavior occurs when running an even simpler query:

```
dfg.sparql("""
PREFIX  schema: <http://schema.org/>
PREFIX  rdf:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  xml:  <http://www.w3.org/XML/1998/namespace>
PREFIX  dm:   <http://gsk-kg.rdip.gsk.com/dm/1.0/>
PREFIX  prism: <http://prismstandard.org/namespaces/basic/2.0/>

select ?d
WHERE{
  ?d a dm:Document .

}
LIMIT 10
""").show(10,false)
```

Entire data set is scanned before returning 10 results

**Comment by patofp** [comment]
From the details:
- Query 1 -> Duration: 26 min
- Query 9 -> Duration: 34s

If that's correct, at first look I will say that is the merge sort is causing that times. If my memory doesn't fail I think we introduce a OrderBy when LIMIT statement so I think that is causing the merge sort step.

**Comment by JNKHunter** [comment]
@patofp Looking at OrderBy sounds like a good first step!

Some additional info: Query 9 was run on a much smaller data set (that's why it ran for only 34 seconds) however the problem persists. The entire data set in query 9 is scanned (175 million rows) before returning 10 results .

**Comment by patofp** [comment]
In that case the ordering losses strength as a possible cause of the performance issue as in Query 9 there is no sort on the DAG of that query. Anyway it is worth to take a look.

Another thing is that I think that the normal behaviour is to scan all the rows (175 millions) because without any heuristic the engine can't know whether inside WHERE statement is any operation or filter that forces to scan all the records. What I mean is that the LIMIT is a query modifier that constraints the output data from the already processed data in the WHERE clause.

I think that the behaviour you expect @JNKHunter is that the LIMIT is done while evaluating the WHERE clause. So I think this could be a candidate to optimize.

**Comment by JNKHunter** [comment]
Thanks @patofp, that makes sense.

From a user perspective, a fast LIMIT and OFFSET  are critical for data analysis, and a top priority.

Lacking a heuristic, the default behavior of LIMIT in Spark uses an exponential progression. Data is scanned in larger and larger chunks until the LIMIT is fulfilled. For example, here is the progression of a "needle in a haystack" query on 1.5TB of data using Sparl SQL:

![image](https://user-images.githubusercontent.com/2665766/114544655-eafce800-9c28-11eb-8825-b40dd4802d32.png)

**Comment by JNKHunter** [comment]
By the way, this data was run on flat .nt files. I have not yet tested on Parquet where the behavior may be different.

**Comment by patofp** [comment]
> From a user perspective, a fast LIMIT and OFFSET are critical for data analysis, and a top priority.

Indeed, it is seems very useful for data exploration.

> the default behavior of LIMIT in Spark uses an exponential progression

Oh, didn't knew about this feature Spark has but it makes a lot of sense. We are making use of Spark Dataframe limit operation so we should have the benefits from it.

Thaks @JNKHunter, I suppose in depth analysis should be done here.
