### ISSUE TITLE
Add support for STRENDS string function 

### ISSUE THREAD

**Issue by patofp** [gsk-aiops/bellman#268]
https://www.w3.org/TR/sparql11-query/#func-strings

**Comment by JNKHunter** [comment]
Reopening: Queries are returning zero results. I believe this is because our unit tests are testing against Scala strings, and not against RDF string literals. RDF string literals have quotes in the string like "this is a string literal"

Correct:

![image](https://user-images.githubusercontent.com/2665766/117368932-3b670e80-ae92-11eb-813a-5638a5227ec8.png)

Incorrect:

![image](https://user-images.githubusercontent.com/2665766/117368985-4a4dc100-ae92-11eb-862b-fb66df8fc8c7.png)

**Comment by patofp** [comment]
@JNKHunter I see no `p` column that should match `<http://gsk-kg.rdip.gsk.com/umls/stringLiteral>` or on input dataframe.

Also there is no `g` column and there is explicit FROM, so if no `g` column exist it wont return results. Can you confirm?

I've tried similiar query with no FROM an it seems to return expected results:

```
"rdf string literals" in {
      val df = List(
        (
          "<http://gsk-kg.rdip.gsk.com/umls/CUI=0000001>",
          "<http://gsk-kg.rdip.gsk.com/dm/1.0/stringLiteral>",
          "Menthol 8.4 MG [Koldets Cough Drop]"
        ),
        (
          "<http://gsk-kg.rdip.gsk.com/umls/CUI=0000002>",
          "<http://gsk-kg.rdip.gsk.com/dm/1.0/stringLiteral>",
          "x-ray of shoulder: erosion on left shoulder (procedure)"
        ),
        (
          "<http://gsk-kg.rdip.gsk.com/umls/CUI=0000003>",
          "<http://gsk-kg.rdip.gsk.com/dm/1.0/stringLiteral>",
          "Carpometacarpal interpositional spacer, bioabsorbable"
        )
      ).toDF("s", "p", "o")

      val query =
        """
          |PREFIX dm: <http://gsk-kg.rdip.gsk.com/dm/1.0/>
          |
          |SELECT ?s ?o
          |WHERE {
          | ?s dm:stringLiteral ?o .
          | FILTER STRENDS(?o, "e") .
          |}
          |""".stripMargin

      val result = Compiler.compile(df, query, config)

      result.right.get.collect.length shouldEqual 1
      result.right.get.collect.toSet shouldEqual Set(
        Row(
          "<http://gsk-kg.rdip.gsk.com/umls/CUI=0000003>",
          "\"Carpometacarpal interpositional spacer, bioabsorbable\""
        )
      )
    }
```

**Comment by JNKHunter** [comment]
@patofp I skipped a few steps in the examples above, so maybe the steps weren't clear enough.

Here is the schema of the dataframe:

![image](https://user-images.githubusercontent.com/2665766/117436015-80278f80-aefc-11eb-8509-94bfa4eefcb5.png)

Here is a sample of the dataframe:

![image](https://user-images.githubusercontent.com/2665766/117436041-87e73400-aefc-11eb-8e6a-31b1ac18a5cb.png)

Here I am selecting only the string literals. As you can see, there exist some string literals that end in "e"

![image](https://user-images.githubusercontent.com/2665766/117436144-a64d2f80-aefc-11eb-80f6-9bed73d3e595.png)

And here is the query that is returning no results:

![image](https://user-images.githubusercontent.com/2665766/117436210-ba912c80-aefc-11eb-8ee8-06f11bbb878e.png)

**Comment by JNKHunter** [comment]
Additional question: Do our string functions work as expected on these cases (presence of language tag, presence/absence of XMLSchema datayptes?
https://www.w3.org/TR/n-triples/#sec-literals
