### ISSUE TITLE
Add support for STRBEFORE string function

### ISSUE THREAD

**Issue by patofp** [gsk-aiops/bellman#269]
https://www.w3.org/TR/sparql11-query/#func-strings

**Comment by JNKHunter** [comment]
Reopening. It appears STRBEFORE treats quotes as part of the string literal:

```
PREFIX dm: <http://gsk-kg.rdip.gsk.com/dm/1.0/>
SELECT ?o ?re
FROM <http://gsk-kg.rdip.gsk.com/umls/>
{
	?s dm:stringLiteral ?o
	BIND(STRBEFORE(?o,"e") as ?re)
}
```

![image](https://user-images.githubusercontent.com/2665766/117364874-75cdad00-ae8c-11eb-8660-d4171ef40a33.png)
