### ISSUE TITLE
Add support for SUBSTR string function

### ISSUE THREAD

**Issue by patofp** [gsk-aiops/bellman#271]
https://www.w3.org/TR/sparql11-query/#func-strings

**Comment by JNKHunter** [comment]
Reopening issue:

```
PREFIX dm:<http://gsk-kg.rdip.gsk.com/dm/1.0/>
SELECT ?o ?re
FROM <http://gsk-kg.rdip.gsk.com/umls/>
{
	?s dm:stringLiteral ?o
	BIND(SUBSTR(?o,4) as ?re)
}
```

It appears the method is treating the leading quote as part of the string.
![image](https://user-images.githubusercontent.com/2665766/117364331-c395e580-ae8b-11eb-91f9-aded3c036508.png)

**Comment by patofp** [comment]
Yeah, I did some testing and I obtain results with final double quotes when I disable RdfFormatting Phase. We should look into this.
