### ISSUE TITLE
Create a SparQL workbook

### ISSUE THREAD

**Issue by pepegar** [gsk-aiops/bellman#345]
There are some limitations to SparQL that may be inconvenient for users of Bellman, we could gather some small hacks to let users circumvent these limitations.

**example**: aggregations only work with typed literals of integer, float, decimal, and double valuess, but if there's the case that the user has a colum of plain numbers, they could use `strdt` to add a type annotation to both operands.

**Comment by patofp** [comment]
[AIPL-3411](https://myjira.gsk.com/browse/AIPL-3411)
