### ISSUE TITLE
Updating Expr ADT

### ISSUE THREAD

**Issue by pepegar** [gsk-aiops/bellman#37]
We're currently representing `Construct` and `Select` as cases in our Expr ADT:

```scala
sealed trait Expr

object Expr {
  final case class BGP(triples:Seq[Triple]) extends Expr
  final case class Triple(s:StringVal, p:StringVal, o:StringVal) extends Expr
  final case class LeftJoin(l:Expr, r:Expr) extends Expr
  final case class FilteredLeftJoin(l:Expr, r:Expr, f:FilterFunction) extends Expr
  final case class Union(l:Expr, r:Expr) extends Expr
  final case class Extend(bindTo:StringLike, bindFrom:StringLike, r:Expr) extends Expr
  final case class Filter(funcs:Seq[FilterFunction], expr:Expr) extends Expr
  final case class Join(l:Expr, r:Expr) extends Expr
  final case class Graph(g:StringVal, e:Expr) extends Expr
  final case class Construct(vars: Seq[VARIABLE], bgp: BGP, r:Expr) extends Expr
  final case class Select(vars: Seq[VARIABLE], r:Expr) extends Expr
}
```

but I don't think they should belong there, as they're not part of the SparQL Algebra.

In the case of Select, we can probably rename it to `Project`, and in the case of Construct, I think we could get rid of it altogether.

**Comment by JNKHunter** [comment]
Agreed. It would make sense to move CONSTRUCT handling to the portion of the code that will be responsible for subgraph output. Also agreed that select should at least be renamed Project.

**Comment by shihch** [comment]
CONSTRUCT could drop. But SELECT should be part of it since nested SELECT would be in the Algebra.

**Comment by shihch** [comment]
BTW, in Jena, Construct and Select * won't show in the compiled algebra.

**Comment by pepegar** [comment]
I think we can close this one, as it was mostly performed in #39
