### ISSUE TITLE
Change description of the project

### ISSUE THREAD

**Issue by pepegar** [gsk-aiops/bellman#60]
<img width="307" alt="Screenshot 2021-02-23 at 08 23 32" src="https://user-images.githubusercontent.com/694179/108813006-6db1e100-75b0-11eb-8c76-604652785df2.png">

We have a fully featured compiler now in `bellman`, not only the parser side, so we can change the description of the project ☝️

**Comment by JNKHunter** [comment]
Done. Will spend some time this week on a proper intro.
