### ISSUE TITLE
Add support for default graph

### ISSUE THREAD

**Issue by JNKHunter** [gsk-aiops/bellman#91]
Specification here:
https://www.w3.org/TR/rdf-sparql-query/#unnamedGraph

Please call meeting w AiOps team to discuss. Work with @shihch and @puremachinery afterwards for testing.

**Comment by patofp** [comment]
I've been researching on this issue that relates with #90 so the conclusions are valid for both issues.

There are some concepts about  **default and named graphs** that can be a little tricky, so I found this resource [default graphs demystified](https://blog.metaphacts.com/the-default-graph-demystified) where they explain how this works behind the scenes.

As they point out it seems that the way [Apache Jena Fuseki](https://jena.apache.org/documentation/fuseki2/) implicitly generate the dataset from default and named graphs is _**exclusive**_ by default. This is different in other Sparql endpoints as in RDF4J Eclipse and the behavior is not specified how in the standard how it should be, so both behaviors **inclusive** and **exclusive** are considered to be both correct. Also most of this endpoints have options to change the behavior for this scenario.

The same not happen when the dataset is generated explicitly from the Sparql query through the usage fo **FROM** for default graphs and **FROM NAMED** for named graphs and also **GRAPH** statement to refer to a particular graph or graphs. 

So, how this could be implemented in our engine. Right now our engine receives as input the Dataframe that contains all of the default graph with the triples as columns `(s, p, o)` . The are, at least, two possible solutions:

- Pass a collection of Dataframes (this doesn't make much sense)
- Add a column to the Dataframe so it will have `(g, s, p, o)` where `g` is the name of the graph.

This is certainly related to the task @shihch is doing about the preprocessing of the query and generating the cache from Apache Hudi that will be passed to the engine, this cache could be in this format `(g, s, p, o)` and we can adapt the engine to match specific graphs.

So at this point I think it is better to have that meeting and discuss it before going any further on this task. What do you think @JNKHunter?

Also I wanted to show how we can extract the graphs URIs from the query with Apache Jena.

When we parse the query:
```
val query = QueryFactory.create(sparql)
query.getNamedGraphURIs // This will contain the URI of the Named grapsh
query.getGraphURIs // This will contain the defualt graph URI
```

**Comment by JNKHunter** [comment]
Let's have a meeting to discuss. Operating over S,P,O,G quads will likely be the way to go here.
